List<String>ilahiisimleri=[
  "Ağlama KaranFilim",
  "Ben Minik Bir Kulum",
  "Bu Akli Fikriyle Mevla Bulunmaz",
  "Canım Kurban Olsun Sana",
  "Cennet Evi",
  "Dil Hanesi Pür Nur Olur ",
  "Er Yarın Hak Divanında Bell'olur",
  "Gel Gör Beni Aşk Neyledi",
  "Gönül Kuşu",
  "Islandı Seccadem",
  "Kara Bulutlarda Bir Şimşek Çaktı",
  "Kara Yüzüm Süre Gelsem",
  "Mevlam Sana Ersem Diye",
  "Salavatı Şerife",
  "Seher Vakti Bülbüller",
  "Tala'a Al-Badru 'Alayna",
  "Tesbihat",
  "Yakma Yarabbi",
  "Yan Yüreğim Yan",
];